apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: exam-melisaatis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: melisaatis/big_data_and_ai-24_may_api:versie1

        env:
        - name: NAME
          value: backend
        - name: DATE
          value: $(date)
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: exam-melisaatis
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 30001
  type: NodePort



    